// AUTO-GENERATED trust policy content (sourced from the live Trust Centre).
// Edit here to update policy copy; the /trust/[slug] route renders these.

export type PolicyBlock =
  | { k: "h"; t: string }
  | { k: "p"; t: string }
  | { k: "ul" | "ol"; items: string[] };

export type Policy = {
  slug: string;
  title: string;
  blurb: string;
  intro?: string;
  lastUpdated: string;
  blocks: PolicyBlock[];
};

export const policies: Policy[] = [
  {
    slug: "information-security-policy",
    title: "Information Security Policy",
    blurb: "How we protect the confidentiality, integrity and availability of information across people, process and technology.",
    lastUpdated: "12 May 2026",
    blocks: [
      { k: "h", t: `1. Purpose` },
      { k: "p", t: `The purpose of this Information Security Policy is to establish and maintain the confidentiality, integrity, and availability of Vortex IQ’s information assets and to protect the organisation, its customers, partners, and employees from information security risks.` },
      { k: "h", t: `2. Scope` },
      { k: "p", t: `This policy applies to all employees, contractors, partners, and third parties who access or manage Vortex IQ’s information systems, data, and infrastructure, including all physical and digital assets.` },
      { k: "h", t: `3. Information Security Objectives` },
      { k: "ul", items: [`Protect information from unauthorised access, disclosure, alteration, and destruction.`, `Ensure the confidentiality, integrity, and availability of all data processed or stored by Vortex IQ.`, `Comply with applicable legal, regulatory, and contractual security requirements.`, `Promote a culture of security awareness and responsibility.`] },
      { k: "h", t: `4. Roles and Responsibilities` },
      { k: "ul", items: [`<strong>Information Security Officer (ISO):</strong> Oversees the implementation, monitoring, and enforcement of security policies and procedures.`, `<strong>Employees and Contractors:</strong> Responsible for complying with this policy and reporting any security incidents or vulnerabilities promptly.`, `<strong>IT Team:</strong> Implements technical controls, monitors systems, and manages access rights.`, `<strong>Third Parties:</strong> Must adhere to Vortex IQ’s security requirements through contractual agreements.`] },
      { k: "h", t: `5. Access Control` },
      { k: "ul", items: [`Access to systems and data is granted on a need-to-know and least privilege basis.`, `Strong authentication mechanisms, including multi-factor authentication (MFA), are required for all remote and privileged access.`, `User access rights are regularly reviewed and promptly revoked upon termination or role change.`] },
      { k: "h", t: `6. Data Protection` },
      { k: "ul", items: [`All sensitive and personal data must be encrypted in transit and at rest using industry-standard encryption protocols.`, `Data backups are performed regularly and stored securely to enable recovery in case of data loss or corruption.`, `Data retention and deletion practices comply with applicable regulations and contractual obligations.`] },
      { k: "h", t: `7. Network and System Security` },
      { k: "ul", items: [`Firewalls, intrusion detection/prevention systems, and secure network architecture are employed to protect systems.`, `Regular vulnerability assessments and penetration tests are conducted to identify and remediate security weaknesses.`, `Software and systems are kept up to date with security patches and updates.`] },
      { k: "h", t: `8. Incident Management` },
      { k: "ul", items: [`All security incidents and suspected breaches must be reported immediately to the Information Security Officer.`, `An incident response plan is maintained and regularly tested to ensure timely containment, investigation, and resolution of incidents.`, `Lessons learned from incidents are used to improve security measures continuously.`] },
      { k: "h", t: `9. Physical Security` },
      { k: "ul", items: [`Access to physical premises housing critical infrastructure is restricted and monitored.`, `Visitors are required to sign in and be escorted while on premises.`] },
      { k: "h", t: `10. Employee Awareness and Training` },
      { k: "ul", items: [`All employees and contractors receive mandatory security awareness training upon onboarding and periodically thereafter.`, `Training covers data protection, phishing awareness, secure password practices, and incident reporting.`] },
      { k: "h", t: `11. Compliance and Auditing` },
      { k: "ul", items: [`Compliance with this policy is monitored through regular internal audits and reviews.`, `Non-compliance may result in disciplinary actions, up to and including termination.`] },
      { k: "h", t: `12. Policy Review` },
      { k: "p", t: `This policy is reviewed at least annually or following significant changes to technology, business processes, or regulatory requirements.<br/><br/><br/>` },
    ],
  },
  {
    slug: "data-protection-addendum",
    title: "Data Protection Addendum (DPA)",
    blurb: "Controller/processor responsibilities, security measures and international-transfer safeguards for personal data.",
    intro: `This Data Protection Addendum ("Addendum") forms part of the agreement between <strong>Vortex IQ Limited</strong> ("Data Processor") and the Customer ("Data Controller") concerning the processing of personal data under applicable data protection laws, including the UK GDPR and the Data Protection Act 2018.`,
    lastUpdated: "12 May 2026",
    blocks: [
      { k: "h", t: `1. Definitions` },
      { k: "ul", items: [`<strong>Personal Data</strong> means any information relating to an identified or identifiable natural person.`, `<strong>Processing means</strong> any operation performed on Personal Data, whether automated or manual.`, `<strong>Data Controller</strong> means the entity that determines the purposes and means of processing Personal Data.`, `<strong>Data Processor</strong> means <strong>Vortex IQ Limited</strong>, the entity that processes Personal Data on behalf of the Data Controller.`] },
      { k: "h", t: `2. Data Processing` },
      { k: "p", t: `Vortex IQ shall process Personal Data only on documented instructions from the Data Controller, including with regard to transfers of Personal Data to a third country or an international organisation, unless required to do so by law.` },
      { k: "h", t: `3. Purpose of Processing` },
      { k: "p", t: `Personal Data will be processed solely for the purpose of providing the services agreed under the main agreement.` },
      { k: "h", t: `4. Data Security` },
      { k: "p", t: `Vortex IQ shall implement appropriate technical and organisational measures to protect Personal Data against unauthorised or unlawful processing, accidental loss, destruction, or damage, in line with industry best practices and the security standards of Amazon Web Services (AWS).` },
      { k: "h", t: `5. Sub-processors` },
      { k: "p", t: `Vortex IQ may engage sub-processors, including AWS, for the provision of services. Vortex IQ shall ensure that sub-processors are bound by data protection obligations consistent with this Addendum.` },
      { k: "h", t: `6. Data Subject Rights` },
      { k: "p", t: `Vortex IQ shall assist the Data Controller in responding to requests from data subjects exercising their rights under applicable data protection laws.` },
      { k: "h", t: `7. Data Breach Notification` },
      { k: "p", t: `Vortex IQ shall notify the Data Controller without undue delay upon becoming aware of any personal data breach affecting the Data Controller’s Personal Data.` },
      { k: "h", t: `8. Data Transfers` },
      { k: "p", t: `Vortex IQ shall ensure that any transfer of Personal Data outside the UK or European Economic Area (EEA) complies with applicable data protection laws, including using appropriate safeguards such as Standard Contractual Clauses.` },
      { k: "h", t: `9. Data Retention and Deletion` },
      { k: "p", t: `Upon termination or expiry of the agreement, Vortex IQ shall, at the choice of the Data Controller, delete or return all Personal Data processed on behalf of the Data Controller, unless retention is required by law.` },
      { k: "h", t: `10. Audit Rights` },
      { k: "p", t: `The Data Controller shall have the right to audit Vortex IQ’s compliance with this Addendum upon reasonable notice and during normal business hours.<br/><br/><br/>` },
    ],
  },
  {
    slug: "sub-processors",
    title: "Sub-processors",
    blurb: "The vetted cloud and AI sub-processors we use to run the platform, with regions and retention terms.",
    intro: `Vortex IQ Limited ("Vortex IQ") engages the sub-processors listed below to deliver the Service. All sub-processors are bound by data-protection obligations consistent with our <a href="/trust/data-protection-addendum">Data Protection Addendum</a> and applicable UK and EU data-protection law. Customer data is processed transiently for the requested action only and is not used to train any third-party foundation model.`,
    lastUpdated: "12 May 2026",
    blocks: [
      { k: "h", t: `1. Infrastructure & hosting` },
      { k: "ul", items: [`<strong>Amazon Web Services (AWS)</strong>: Primary hosting, compute and storage. Region: UK / EU. Retention: per the main agreement; data deleted or returned on termination.`, `<strong>Google Cloud Platform (GCP)</strong>: Secondary hosting and Vertex AI services. Region: UK / EU. Retention: per the main agreement.`] },
      { k: "h", t: `2. Foundation model providers (LLM inference)` },
      { k: "p", t: `Vortex IQ is model-agnostic and routes per task type. For each provider, customer inputs and outputs are not used to train the provider’s foundation models under the contractual terms applicable to our usage.` },
      { k: "ul", items: [`<strong>Anthropic</strong> (Claude family): LLM inference for content generation, classification and ranking. Endpoint: enterprise API. Retention: Zero Data Retention under Anthropic’s enterprise terms; inputs and outputs are not used to train Anthropic models.`, `<strong>OpenAI</strong> (GPT family): LLM inference for content generation and reasoning. Endpoint: enterprise / commercial API. Retention: inputs and outputs are not used to train OpenAI models under the applicable API terms; Zero Data Retention is enabled on eligible endpoints.`, `<strong>Google</strong> (Gemini family, via Vertex AI / Google AI for Workspace): LLM inference for multimodal and image-understanding tasks. Endpoint: enterprise API. Retention: customer data is not used to train Google’s foundation models under Google’s enterprise terms.`] },
      { k: "p", t: `<strong>Note on Moonshot AI (Kimi):</strong> Kimi is evaluated inside Vortex IQ’s internal research lab for proof-of-concept testing only. Kimi is <strong>not</strong> used in the production application and does not process customer data.` },
      { k: "h", t: `3. International transfers` },
      { k: "p", t: `Where personal data is transferred outside the United Kingdom or the European Economic Area, Vortex IQ relies on appropriate safeguards, including the UK International Data Transfer Agreement and the European Commission’s Standard Contractual Clauses, supported by a transfer impact assessment where required.` },
      { k: "h", t: `4. Changes to this list` },
      { k: "p", t: `Vortex IQ will update this page when sub-processors are added or removed. Material changes will be communicated to customers via their primary contact, in accordance with the notice provisions of the main agreement and the <a href="/trust/data-protection-addendum">Data Protection Addendum</a>.` },
      { k: "h", t: `5. Contact` },
      { k: "p", t: `Questions about this sub-processor list, or requests for further information (including signed copies of any of the above contractual commitments), can be sent to <a href="mailto:privacy@vortexiq.ai">privacy@vortexiq.ai</a>.` },
    ],
  },
  {
    slug: "incident-response-and-breach-notification-policy",
    title: "Incident Response and Breach Notification Policy",
    blurb: "How we detect, contain, investigate and notify on security incidents and personal-data breaches.",
    intro: `This policy sets out how Vortex IQ detects, responds to, contains and learns from security incidents, and how we notify affected customers and regulators within defined timeframes.`,
    lastUpdated: "15 June 2026",
    blocks: [
      { k: "h", t: `1. Definition` },
      { k: "ul", items: [`<strong>Security incident:</strong> any event that compromises, or may compromise, the confidentiality, integrity or availability of Vortex IQ systems or customer data.`, `<strong>Personal data breach:</strong> a security incident leading to the accidental or unlawful destruction, loss, alteration, unauthorised disclosure of, or access to, personal data (UK GDPR).`] },
      { k: "p", t: `<strong>2. Response team and roles</strong><br/>` },
      { k: "ul", items: [`An <strong>Incident Lead</strong> coordinates the response.`, `Engineering performs containment, eradication and recovery.`, `Our privacy owner assesses notification obligations.`, `Executive management owns customer and external communications.`] },
      { k: "p", t: `<strong>3. Severity levels</strong>` },
      { k: "ul", items: [`<strong>Critical</strong>: confirmed breach of customer data, or major outage. Immediate response.`, `High: likely breach or significant degradation.`, `Medium / Low: contained or limited-impact events.`] },
      { k: "h", t: `4. Response phases` },
      { k: "ul", items: [`<strong>Detect and report</strong>. Staff and monitoring report suspected incidents without delay.`, `<strong>Triage</strong>. The Incident Lead assesses severity and scope and opens an incident record.`, `<strong>Contain</strong>. Limit impact: isolate systems, disable affected capabilities, revert changes via rollback where relevant.`, `<strong>Eradicate</strong>. Remove the root cause.`, `Recover. Restore service and verify integrity, using the <a href="file:///C:/trust/disaster-recovery-plan">Disaster Recovery Plan</a> where needed.`, `<strong>Post-incident review</strong>. Document root cause, timeline and corrective actions promptly after resolution.`] },
      { k: "h", t: `5. Breach notification` },
      { k: "p", t: `Where a personal data breach affecting customer data is confirmed, Vortex IQ will notify the affected customer <strong>without undue delay and within 72 hours</strong> of confirming the breach. Notification will include, as far as known, the nature of the breach, the data and individuals affected, likely consequences, and the measures taken or proposed.` },
      { k: "p", t: `<br/>As a processor, Vortex IQ supports customers (as controllers) in meeting their own regulatory notification duties. Where Vortex IQ is the controller, it will notify the ICO and data subjects as required by UK GDPR.` },
      { k: "h", t: `6. Evidence and communications` },
      { k: "p", t: `Logs and evidence are preserved to support investigation and any regulatory or contractual requirement. Customer communications are owned by executive management; the security contact and, where relevant, the status page (<a href="https://monitor.vortexiq.ai">monitor.vortexiq.ai</a>) keep customers informed.` },
      { k: "h", t: `7. Testing` },
      { k: "p", t: `The plan is tested through tabletop or simulation exercises and updated based on findings.<br/><br/><br/>` },
    ],
  },
  {
    slug: "secure-sdlc-and-change-management-policy",
    title: "Secure SDLC and Change Management Policy",
    blurb: "Secure development, code review, testing and controlled, reversible change management.",
    intro: `This policy ensures software is developed, tested and released securely, and that changes to customer-facing systems are controlled, reviewed and reversible. It is especially relevant where Vortex IQ supports code, theme and configuration deployment for customers.`,
    lastUpdated: "15 June 2026",
    blocks: [
      { k: "h", t: `1. Scope` },
      { k: "p", t: `All Vortex IQ source code, infrastructure-as-code, AI prompts and configurations that affect the platform or customer environments.` },
      { k: "h", t: `2. Secure development` },
      { k: "ul", items: [`<strong>Version control</strong>. All code is held in version control with protected main branches.`, `<strong>Peer review</strong>. Changes require review and approval by a second engineer before merge.`, `<strong>Secrets management</strong>. Secrets are never committed to source; they are held in a managed secrets store.`, `<strong>Dependency and static analysis</strong>. Dependencies are scanned for known vulnerabilities and static analysis runs in the pipeline.`, `<strong>Least privilege</strong>. Build and deploy systems use scoped, audited credentials.`] },
      { k: "p", t: `<strong>3. Testing</strong>` },
      { k: "ul", items: [`Automated tests run in the pipeline before release.`, `Security-relevant changes receive additional review.`, `Changes are validated in a <strong>staging environment</strong> that mirrors production before they reach production.`] },
      { k: "h", t: `4. Roles and Responsibilities` },
      { k: "ul", items: [`<strong>Environment separation</strong>. Development, staging and production are separated; no untested change is promoted directly to production.`, `<strong>Approval</strong>. Production changes are approved and recorded, with the change, author and approver logged.`, `<strong>Customer-facing deployments</strong>. Where Vortex IQ deploys code, themes or data changes into a customer&#x27;s environment, the change is staged and tested first (StagingPro, DryRunPro) and can be reverted in one click (RollbackPro). Nothing reaches a customer&#x27;s production without the appropriate approval.`, `<strong>Emergency changes</strong>. Expedited changes follow a defined break-glass process and are reviewed retrospectively.`, `Rollback. Every production change has a defined rollback path.`] },
      { k: "h", t: `5. AI and model changes` },
      { k: "p", t: `Changes to models, prompts or autonomous behaviour that affect customer-facing output follow this policy and the <a href="/trust/ai-model-governance-policy">AI and Model Governance Policy</a>, including evaluation before release.` },
      { k: "h", t: `6. Audit` },
      { k: "p", t: `Change records, approvals and deployment logs are retained and available for audit.<br/><br/><br/>` },
    ],
  },
  {
    slug: "ai-model-governance-policy",
    title: "AI and Model Governance Policy",
    blurb: "How we select, govern and monitor AI models, and keep customer data out of model training.",
    intro: `Vortex IQ is the AI Operating System for e-commerce. This policy sets out how we use artificial intelligence and large language models safely, transparently, and under human control, and how we protect customer data when it is processed by AI.`,
    lastUpdated: "15 June 2026",
    blocks: [
      { k: "h", t: `1. Scope` },
      { k: "p", t: `Applies to all Vortex IQ products and pillars (Nerve Centre, Vortex Mind, Ask Viq, Vortex Agents, Vortex Apps, Vortex Memory) and to all AI models and providers used to deliver them.` },
      { k: "p", t: `<strong>2. Principles</strong><br/>` },
      { k: "ul", items: [`<strong>Human accountability</strong>. AI assists people; it does not replace their authority. A person is accountable for any change to a customer&#x27;s systems.`, `<strong>Least data</strong>. We send the model only the data a task requires.`, `<strong>Transparency</strong>. Customers can see what the AI did, why, and on what evidence.`, `<strong>Safety by default</strong>. Higher-impact actions require stronger controls and explicit approval.`, `<strong>No training on customer data</strong>. Customer data is not used to train models, ours or our providers`] },
      { k: "p", t: `<strong>3</strong>.<strong>Models and providers</strong>` },
      { k: "ul", items: [`Vortex IQ&#x27;s reasoning runs primarily on <strong>Claude, provided by Anthropic</strong>, and also uses <strong>Gemini, provided by Google</strong>, and Vortex IQ&#x27;s own proprietary models, selected according to the task. Third-party models are accessed over secure APIs and listed in our <a href="file:///C:/trust/sub-processors">sub-processor register</a>.`, `<strong>Our model providers do not use API data to train their models, and neither does Vortex IQ.</strong>`, `<strong></strong>New models or providers are assessed against this policy before use.`] },
      { k: "h", t: `4.Data handling in AI processing` },
      { k: "ul", items: [`Inputs sent to the model are limited to what the task needs and are transmitted over encrypted channels.`, `Customer data processed by the model is not retained to improve Vortex IQ models or shared with other customers.`, `Customer data remains logically isolated per tenant.`, `Customers can request deletion of their data in line with the Data Protection Addendum.`] },
      { k: "h", t: `5. Levels of autonomy and human-in-the-loop` },
      { k: "p", t: `Every AI capability operates at one of three levels:` },
      { k: "ol", items: [`<strong>Insights (read-only)</strong>. The AI surfaces information. No change is made.`, `<strong>Recommended Actions</strong>. The AI proposes a change. A person reviews and decides.`, `<strong>Automated Decisions</strong>. The AI executes a change, only for a specific, scoped task the customer has explicitly enabled, with limits and logging.`] },
      { k: "p", t: `By default, nothing that changes a customer&#x27;s store or systems happens without human sign-off. Where automation is enabled, changes are tested in staging first and can be reverted in one click (StagingPro, DryRunPro, RollbackPro).` },
      { k: "h", t: `6. Guardrails and safety controls` },
      { k: "ul", items: [`<strong>Scoped permissions</strong>. The AI acts only within the connectors, data and actions the customer has authorised, read-only wherever possible.`, `<strong>Input and output handling</strong>. Prompts and outputs are validated, and known prompt-injection and unsafe-output patterns are mitigated.`, `<strong>Restricted actions</strong>. High-impact actions (bulk changes, deletions, financial operations) are gated behind approval and additional confirmation.`, `<strong>Accuracy</strong>. Outputs that drive actions are grounded in the customer&#x27;s own data and cite their evidence; users are told when a result is a model inference rather than a measured value.`, `Rate and scope limits prevent runaway or out-of-scope automation.`] },
      { k: "h", t: `7. Auditability` },
      { k: "p", t: `Every AI-driven recommendation, decision, action and data access is logged with the inputs, the model output, the approver where applicable, and the outcome. Logs are available to the customer.` },
      { k: "h", t: `8. Testing and evaluation` },
      { k: "p", t: `AI capabilities are evaluated before release and monitored in production for quality, safety and drift. Material changes to models or prompts that affect customer-facing behaviour follow our <a href="/trust/secure-sdlc-and-change-management-policy">Secure SDLC and Change Management Policy</a>.` },
      { k: "h", t: `9. Appropriate use, bias and fairness` },
      { k: "p", t: `Vortex IQ uses AI for commerce operations: monitoring, diagnostics, content, and deployment support. We do not use it for prohibited or high-risk decisioning outside that scope. Where outputs could be influenced by bias in source data, we flag the limitation.` },
      { k: "h", t: `10. AI incidents` },
      { k: "p", t: `Suspected unsafe outputs, data exposure through AI, or automation acting out of scope are handled under our <a href="/trust/incident-response-and-breach-notification-policy">Incident Response and Breach Notification Policy</a>, with AI-specific containment (disable the capability, revert via rollback, review logs).<br/><br/><br/>` },
    ],
  },
  {
    slug: "vendor-and-third-party-risk-policy",
    title: "Vendor and Third-party Risk Policy",
    blurb: "How we assess, tier and monitor third-party vendors and sub-processors for security and compliance.",
    intro: `This policy ensures third parties that process Vortex IQ or customer data, or that are critical to the service, meet appropriate security and data-protection standards before and during engagement.`,
    lastUpdated: "15 June 2026",
    blocks: [
      { k: "h", t: `1. Scope` },
      { k: "p", t: `All vendors, sub-processors and service providers with access to Vortex IQ systems, customer data or personal data, including cloud infrastructure (AWS, Google Cloud) and AI providers (Anthropic, Google).` },
      { k: "p", t: `<strong>2. Principles Risk Tiring</strong><br/>` },
      { k: "ul", items: [`<strong>Tier 1 (high)</strong>: processes customer or personal data, or is critical to availability (e.g. cloud hosting, LLM provider).`, `<strong>Tier 2 (medium)</strong>: limited access to business data.`, `Tier 3 (low): no access to customer or personal data.`] },
      { k: "p", t: `Diligence depth scales with tier.` },
      { k: "p", t: `<strong>3</strong>. <strong>Due diligence before onboarding</strong>` },
      { k: "p", t: `<strong></strong>.For Tier 1 and 2 vendors, before engagement we review:` },
      { k: "ul", items: [`Vortex IQ&#x27;s reasoning runs primarily on Claude, provided by Anthropic, and also uses Gemini, provided by Google, and Vortex IQ&#x27;s own proprietary models, selected according to the task. Third-party models are accessed over secure APIs and listed in our sub-processor register.`, `Data-protection terms (a DPA where personal data is processed; transfer mechanism such as SCCs or the UK IDTA).`, `Data location and residency.`, `Breach notification commitments.`] },
      { k: "h", t: `4. Contractual requirements` },
      { k: "p", t: `Tier 1 and 2 vendors must be bound by contractual confidentiality and, where personal data is processed, a DPA with obligations no less protective than those Vortex IQ owes its customers. AI and LLM providers must contractually confirm that customer data is not used to train their models.` },
      { k: "h", t: `5. Sub-processor management` },
      { k: "p", t: `Sub-processors that process customer personal data are listed publicly at <a href="/trust/sub-processors">vortexiq.ai/trust/sub-processors</a>. Customers receive at least 30 days&#x27; notice of additions or replacements and may object on reasonable data-protection grounds, as set out in the Data Protection Addendum.` },
      { k: "h", t: `6. Ongoing monitoring and offboarding` },
      { k: "p", t: `Tier 1 vendors are reviewed for continued compliance, certification currency and any reported incidents. Material issues are escalated to the policy owner. On termination, vendor access is revoked promptly and, where they hold Vortex IQ or customer data, return or secure deletion is confirmed.<br/><br/><br/>` },
    ],
  },
  {
    slug: "corporate-security",
    title: "Corporate Security Plan",
    blurb: "Organisational, physical and personnel security controls that protect the business and its assets.",
    intro: `<strong>Effective Date: </strong>1 July 2023<strong><br/>Approved by: </strong>Senior Management Team`,
    lastUpdated: "12 May 2026",
    blocks: [
      { k: "h", t: `1. Purpose` },
      { k: "p", t: `The purpose of this policy is to establish a framework for protecting Vortex IQ’s information assets, systems, and infrastructure from security threats, ensuring confidentiality, integrity, and availability. This policy supports our commitment to safeguarding client data, intellectual property, and company reputation.` },
      { k: "h", t: `2. Scope` },
      { k: "p", t: `This policy applies to all employees, contractors, consultants, and temporary staff (collectively “staff”) who access or manage Vortex IQ’s systems, data, and physical premises.` },
      { k: "h", t: `3. Senior Management Commitment` },
      { k: "p", t: `Senior management fully supports this policy and is committed to providing necessary resources and leadership to maintain a strong security posture.` },
      { k: "h", t: `4. Security Responsibilities` },
      { k: "ul", items: [`All staff must read, understand, and comply with this policy.`, `Staff will acknowledge this policy during onboarding and annually thereafter.`, `Security incidents or breaches must be reported immediately to the designated Security Officer.`, `Access to systems and data is granted on a least-privilege basis and regularly reviewed.`] },
      { k: "h", t: `5. Data Protection` },
      { k: "ul", items: [`Sensitive and personal data must be handled in compliance with applicable laws and company procedures.`, `Data must be stored securely using encryption where appropriate.`, `Data access is limited to authorised personnel only.`] },
      { k: "h", t: `6. Access Control` },
      { k: "ul", items: [`Unique user credentials must be used; sharing of accounts is prohibited.`, `Multi-factor authentication (MFA) is mandatory for access to critical systems.`, `Passwords must meet complexity requirements and be changed regularly.`] },
      { k: "h", t: `7. Physical Security` },
      { k: "ul", items: [`Access to company premises and data centres is controlled and monitored.`, `Visitors must be authorised and accompanied at all times.`] },
      { k: "h", t: `8. Acceptable Use` },
      { k: "ul", items: [`Company systems and devices must be used responsibly and primarily for business purposes.`, `Staff must not install unapproved software or connect unauthorised devices.`] },
      { k: "h", t: `9. Incident Management` },
      { k: "ul", items: [`All security incidents must be reported promptly following the Incident Response procedure.`, `The company will investigate incidents and take corrective actions to prevent recurrence.`] },
      { k: "h", t: `10. Training and Awareness` },
      { k: "ul", items: [`Security awareness training will be provided to all staff during onboarding and refreshed annually.`, `Staff are responsible for maintaining their security knowledge and adhering to best practices.`] },
      { k: "h", t: `11. Policy Compliance` },
      { k: "ul", items: [`Non-compliance with this policy may result in disciplinary action, up to and including termination.`, `Regular audits and reviews will ensure compliance with this policy.`] },
      { k: "h", t: `12. Policy Review` },
      { k: "p", t: `This policy will be reviewed annually or as needed due to changes in regulatory, technical, or organisational conditions.<br/><br/><br/>` },
    ],
  },
  {
    slug: "mobile-device-management-policy",
    title: "Mobile Device Management (MDM) Policy",
    blurb: "Controls for company and BYOD devices that access Vortex IQ systems and data.",
    lastUpdated: "12 May 2026",
    blocks: [
      { k: "h", t: `Purpose:` },
      { k: "p", t: `To ensure the security, integrity, and appropriate use of company data and systems accessed via employee laptops and mobile devices.` },
      { k: "h", t: `Scope:` },
      { k: "p", t: `This policy applies to all laptops, tablets, smartphones, and other mobile devices issued by the company or used to access company resources.` },
      { k: "h", t: `Policy Statement:` },
      { k: "h", t: `1. Device Management:` },
      { k: "p", t: `All employee laptops provided by the company are enrolled in the organisation’s Mobile Device Management (MDM) system. This enables centralised control, configuration, and security enforcement.` },
      { k: "h", t: `2. Monitoring:` },
      { k: "p", t: `The company monitors device compliance with security policies, including but not limited to:` },
      { k: "ul", items: [`Operating system updates and patching`, `Antivirus and anti-malware status`, `Encryption status`, `Installation of approved software only`, `Usage of VPN and secure connections`] },
      { k: "h", t: `3. Access Control:` },
      { k: "p", t: `Devices must be password protected, and the company enforces multi-factor authentication where applicable. Devices found to be non-compliant may have access to company systems restricted or revoked until compliance is restored.` },
      { k: "h", t: `4. Data Protection:` },
      { k: "p", t: `Company data on employee devices is protected by encryption and remote wipe capabilities in the event of loss or theft. Employees must report lost or stolen devices immediately.` },
      { k: "h", t: `5. Privacy:` },
      { k: "p", t: `While the company monitors devices to ensure security and compliance, it respects employee privacy by limiting monitoring to work-related data and activity. Personal data stored on devices is not accessed without consent unless legally required.` },
      { k: "h", t: `6. User Responsibilities:` },
      { k: "p", t: `Employees are required to use company devices responsibly, adhere to security guidelines, and not attempt to circumvent management controls.` },
      { k: "h", t: `7. Policy Compliance:` },
      { k: "p", t: `Violation of this policy may result in disciplinary action, up to and including termination of employment.` },
    ],
  },
  {
    slug: "business-continuity-plan",
    title: "Business Continuity Plan",
    blurb: "How we keep critical services running and recover operations during a disruption.",
    lastUpdated: "12 May 2026",
    blocks: [
      { k: "h", t: `1. Purpose` },
      { k: "p", t: `The purpose of this <strong>Business Continuity Management (BCM) Policy</strong> is to ensure that Vortex IQ maintains the ability to continue its critical operations during and after a disruptive event. This policy outlines the procedures, responsibilities, and resources required to safeguard the business and maintain uninterrupted services for our clients, particularly with regard to our AI-powered ecommerce automation solutions.` },
      { k: "h", t: `2. Scope` },
      { k: "p", t: `This policy applies to all critical business functions, processes, and systems within Vortex IQ. It includes all departments, staff, contractors, and third-party vendors involved in delivering the company’s services. The policy is designed to protect Vortex IQ’s operations in the event of business disruptions such as natural disasters, cyber-attacks, technology failures, or any unforeseen circumstances that may impact our ability to deliver services.` },
      { k: "h", t: `3. Objectives` },
      { k: "p", t: `The key objectives of this BCM policy are to:` },
      { k: "ul", items: [`Ensure the safety of employees, contractors, and visitors during a disruption.`, `Minimise the impact of business interruptions on clients, services, and revenue.`, `Establish recovery strategies to restore critical services and infrastructure as quickly as possible.`, `Comply with relevant legal, regulatory, and contractual obligations regarding business continuity.`, `Provide a clear and effective communication strategy during and after an incident.`] },
      { k: "h", t: `4. Key Responsibilities` },
      { k: "ul", items: [`<strong>Business Continuity Manager:</strong> Responsible for the overall implementation, monitoring, and testing of the BCM plan. Ensures coordination of recovery efforts and communication during a disruption.`, `<strong>Executive Management:</strong> Oversee the business continuity strategy and allocate the necessary resources to ensure its success.`, `<strong>All Employees:</strong> Required to understand and follow the procedures outlined in this policy. Employees must participate in training, awareness programs, and continuity tests.`, `<strong>IT Department:</strong> Responsible for ensuring the availability, security, and integrity of Vortex IQ&#x27;s technology infrastructure, including cloud-based systems, data backups, and recovery plans.`] },
      { k: "h", t: `5. Risk Assessment and Impact Analysis` },
      { k: "p", t: `Vortex IQ regularly conducts risk assessments and business impact analyses (BIA) to identify potential threats and vulnerabilities to its operations. These analyses include:` },
      { k: "ul", items: [`Identification of critical business processes and functions.`, `Evaluation of potential impacts of disruptions on these functions.`, `Assessment of the likelihood and severity of various disruptive scenarios.`, `Development of strategies to mitigate identified risks.`] },
      { k: "h", t: `6. Business Continuity Strategy` },
      { k: "ul", items: [`<strong>Incident Response:</strong> A defined process for assessing and responding to incidents that could disrupt business operations. This includes immediate actions to mitigate damage, such as isolating affected systems, notifying stakeholders, and activating recovery procedures.`, `<strong>Technology Continuity:</strong> Vortex IQ employs redundant systems, off-site backups, and cloud-based solutions to ensure service availability during disruptions. Regular backups of all critical data are stored in multiple secure locations.`, `<strong>Workplace Continuity:</strong> In the event that Vortex IQ&#x27;s primary office is unavailable, we have provisions for remote working, including secure access to business-critical applications and systems. Key personnel will be able to continue work from designated backup locations.`, `<strong>Supply Chain and Vendor Continuity:</strong> We will establish contingency arrangements with our critical suppliers and partners, ensuring they also have robust continuity plans in place to support our operations during disruptions.`, `<strong>Communication Plan:</strong> In case of disruption, Vortex IQ will communicate promptly with stakeholders, including customers, partners, and employees. Regular updates will be provided throughout the recovery process.`] },
      { k: "h", t: `7. Business Continuity Plan (BCP)` },
      { k: "p", t: `The <strong>Business Continuity Plan (BCP)</strong> is a comprehensive document detailing the steps Vortex IQ will take to respond to different types of disruptions. The BCP includes:` },
      { k: "ul", items: [`<strong>Activation Criteria:</strong> Specific conditions under which the BCP will be activated.`, `<strong>Recovery Priorities:</strong> A tiered approach to recovery, prioritising business-critical functions and systems.`, `<strong>Resource Allocation:</strong> Identifying key resources (personnel, equipment, etc.) necessary to restore operations.`, `<strong>Recovery Time Objectives (RTOs):</strong> The maximum acceptable downtime for each critical function.`, `<strong>Recovery Point Objectives (RPOs):</strong> The maximum acceptable data loss measured in time.`] },
      { k: "h", t: `8. Training and Awareness` },
      { k: "p", t: `Vortex IQ will ensure that all employees are trained on business continuity procedures. Regular training sessions, simulations, and awareness campaigns will be conducted to ensure staff are familiar with their roles in the event of a disruption. The company will also maintain ongoing communication regarding updates and improvements to the BCM plan.` },
      { k: "h", t: `9. Testing and Drills` },
      { k: "p", t: `The <strong>BCM Plan</strong> will be regularly tested to ensure it is effective and up-to-date. Vortex IQ will conduct:` },
      { k: "ul", items: [`<strong>Annual BCM Tests:</strong> Simulated disruption scenarios will be run to test the effectiveness of response and recovery procedures.`, `<strong>Technology Drills:</strong> Regular testing of backup systems, disaster recovery infrastructure, and cloud continuity to ensure all systems can be restored within the prescribed RTOs and RPOs.`] },
      { k: "h", t: `10. Monitoring and Review` },
      { k: "p", t: `Vortex IQ&#x27;s BCM policy will be continuously monitored and reviewed on an annual basis or whenever a significant change occurs in the business or external environment. Feedback from testing, incidents, and real-world disruptions will be used to refine the policy and improve preparedness for future disruptions.` },
      { k: "h", t: `11. Documentation and Compliance` },
      { k: "p", t: `This policy will be documented and maintained in accordance with relevant industry standards and regulatory requirements. All stakeholders will have access to the policy and be familiar with their roles in the event of a disruption.` },
      { k: "p", t: `The <strong>Business Continuity Management (BCM) Policy</strong> ensures that Vortex IQ is prepared for any event that could disrupt its ability to provide e-commerce optimisation services to merchants. By following this policy, Vortex IQ is committed to minimising the impact of disruptions, safeguarding our business operations, and maintaining our reputation as a trusted provider of AI-driven solutions.` },
    ],
  },
  {
    slug: "disaster-recovery-plan",
    title: "Disaster Recovery Plan",
    blurb: "Multi-cloud, multi-region recovery objectives and procedures for restoring service after an outage.",
    lastUpdated: "12 May 2026",
    blocks: [
      { k: "h", t: `1. Hosting Environment` },
      { k: "p", t: `Vortex IQ’s application is deployed across <strong>Amazon Web Services (AWS), Google Cloud Platform (GCP), and Microsoft Azure</strong>, leveraging the robust and scalable infrastructures of these providers. This multi-cloud approach ensures <strong>high availability, data protection, regulatory compliance, and rapid recovery</strong> of business-critical systems. Each platform provides a broad set of disaster recovery features that together form the foundation of Vortex IQ’s continuity strategy.` },
      { k: "h", t: `2. Disaster Recovery Topology` },
      { k: "ul", items: [`<strong>Multi-Cloud, Multi-Region Architecture</strong><br/>Vortex IQ operates in multiple regions across AWS (US-East, EU-West), GCP (US-Central, Europe-West), and Azure (East US, West Europe). This <strong>geo-redundant, multi-cloud topology</strong> minimises the risk of downtime due to provider-specific or regional failures. Critical workloads and applications are replicated across clouds and regions for seamless continuity.`, `<strong>Data Replication and Backup</strong><br/>Business-critical data, including application databases and user data, is continuously replicated using native services such as <strong>Amazon RDS/S3, Google Cloud SQL/Cloud Storage, and Azure SQL Database/Blob Storage</strong>. Automated daily backups are securely stored with <strong>encryption at rest and in transit</strong>, ensuring data integrity, confidentiality, and compliance with industry standards.`, `<strong>Automated Failover and Load Balancing</strong><br/>Traffic distribution and failover are managed via <strong>AWS Elastic Load Balancing (ELB), Google Cloud Load Balancer, and Azure Front Door</strong>. In the event of a regional outage, traffic is automatically rerouted to healthy environments, ensuring uninterrupted service availability and minimal downtime.`, `<strong>Monitoring and Alerting</strong><br/>System health and performance are continuously monitored using <strong>Amazon CloudWatch, Google Cloud Monitoring, and Azure Monitor</strong>. These tools provide proactive alerts, trigger automated failovers, and supply detailed metrics on infrastructure, applications, and user experience.`] },
      { k: "h", t: `3. Recovery Time Objectives (RTO) and Recovery Point Objectives (RPO)` },
      { k: "ul", items: [`<strong>RTO (Recovery Time Objective): </strong>The maximum acceptable downtime for critical business functions is<strong> 4 hours. </strong>Multi-region deployments and automated failover mechanisms ensure restoration within this timeframe.`, `<strong>RPO (Recovery Point Objective):</strong> The maximum acceptable data loss is <strong>1 hour,</strong> achieved through real-time replication and frequent incremental backups across all cloud providers.`] },
      { k: "p", t: `4. <strong>Recovery Strategy</strong>` },
      { k: "ul", items: [`<strong>Active-Active Configuration:</strong><br/>Vortex IQ runs an <strong>active-active disaster recovery model</strong>, with services continuously available across primary and secondary regions in AWS, GCP, and Azure. This design ensures immediate failover without noticeable service interruption.`, `<strong>Failover and Failback</strong><br/>DNS-based failover is managed through <strong>AWS Route 53, Google Cloud DNS, and Azure DNS</strong>. In a disaster, traffic is automatically redirected to backup regions. Once the primary environment is stabilised, controlled <strong>failback procedures</strong> restore operations with minimal disruption.`] },
      { k: "h", t: `5. Security and Compliance` },
      { k: "ul", items: [`<strong>Data Encryption:</strong><br/>All sensitive data is encrypted <strong>at rest and in transit</strong> using provider-specific key management services (AWS KMS, Google Cloud KMS, Azure Key Vault) and <strong>SSL/TLS protocols</strong> for secure communications.`, `<strong>Regulatory Compliance:</strong><br/>Vortex IQ’s environments are built to align with GDPR, SOC 2, and ISO 27001 standards, ensuring compliance with legal and regulatory requirements for data protection across all operating regions.`] },
      { k: "h", t: `6. Disaster Recovery Testing and Continuous Improvement` },
      { k: "ul", items: [`<strong>Regular Testing:</strong><br/>Full disaster recovery tests are performed <strong>every 6 months</strong>, simulating real-world scenarios such as regional outages, database corruption, or cloud service disruption. These exercises validate the effectiveness of failover mechanisms, backups, and communication protocols.`, `<strong>Post-Test Review:</strong><br/>After each test, a <strong>comprehensive review</strong> is conducted to document recovery times, identify improvements, and update the DRP. Lessons learned feed into continuous improvement efforts to ensure the plan evolves alongside infrastructure changes.`] },
      { k: "h", t: `7. Communication and Reporting` },
      { k: "ul", items: [`<strong>Disaster Recovery Communication:</strong><br/>In the event of a disruption, automated alerts are sent through <strong>AWS SNS, Google Pub/Sub, and Azure Service Bus</strong>, notifying internal teams, customers, and key third-party partners. Updates are disseminated via Slack, email, and other communication channels.`, `<strong>Reporting and Documentation:</strong><br/>Following each disaster recovery test or real incident, <strong>detailed reports</strong> are produced outlining recovery timelines, remediation steps, and outcomes. Reports are archived for compliance and used to refine processes over time.`] },
      { k: "h", t: `Summary` },
      { k: "p", t: `By leveraging a multi-cloud, multi-region architecture across AWS, GCP, and Azure, Vortex IQ ensures business continuity with redundant systems, real-time data replication, automated failover, and proactive monitoring. This disaster recovery plan guarantees resilience, regulatory compliance, and reliable service delivery under any disruption scenario.<br/><br/><br/><br/>` },
    ],
  },
];

export const policyBySlug = Object.fromEntries(policies.map((p) => [p.slug, p]));
export const policySlugs = policies.map((p) => p.slug);
